name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v2

      - name: Installer Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installer les dépendances
        run: npm install cypress

      - name: Exécuter les tests Jest
        run: npm test

      - name: Exécuter les tests Cypress
        run: npm run cypress:run
